apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: develop
  labels:
    deployment: frontend
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
        ports:
        - name:  web
          containerPort:  8000
          protocol: TCP
        resources:
          requests:
            cpu: "100m"
            memory: "50M"
          limits:
            cpu: "200m"
            memory: "100M"
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: nginx-config
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-develop-frontend-config
      initContainers:
      - name: init-busybox
        image: busybox
        imagePullPolicy: IfNotPresent
        command:
        - sleep
        - "120"
        resources:
          requests:
            cpu: "10m"
            memory: "20M"
          limits:
            cpu: "20m"
            memory: "40M"
