---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota-develop
  namespace: develop
spec:
  hard:
    pods: "10"
    limits.cpu: "8"
    limits.memory: "32G"
    services: "3"
    fast.storageclass.storage.k8s.io/requests.storage: 100G
...
