apiVersion: v1
kind: Service
metadata:
  name: mysql-headless-svc
  namespace: develop
spec:
  clusterIP: None
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 3306
    targetPort: mysqlport
